# Generated by Django 3.2.19 on 2023-05-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0030_auto_20230510_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
