# Generated by Django 3.2.19 on 2023-05-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0032_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
