# Generated by Django 3.2.19 on 2023-05-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplos', '0033_remove_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ManyToManyField(to='ejemplos.Proveedor'),
        ),
    ]
